# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_coming', models.BooleanField(default=False)),
                ('people_attending', models.IntegerField()),
            ],
        ),
    ]
