# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='people_attending',
            field=models.IntegerField(null=True),
        ),
    ]
